apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-bootstrap
  labels:
    app: {{ template "..name" . }}
    chart: {{ template "..chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: bootstrap
spec:
  activeDeadlineSeconds: 2147483647
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: {{ .Release.Name }}-bootstrap
      labels:
        app: {{ template "..name" . }}
        chart: {{ template "..chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        role: bootstrap
    spec:
      terminationGracePeriodSeconds: {{ .Values.bootStrap.terminationGracePeriodSeconds }}
      restartPolicy: Never
      subdomain: {{ .Release.Name }}
      securityContext:
{{ toYaml .Values.bootStrap.securityContext | indent 8 }}
      volumes:
      - name: manifests
        configMap:
          name: {{ .Release.Name }}-cluster
      - name: ssh-key
        secret:
          secretName: {{ .Release.Name }}-ssh-key
          defaultMode: 256
      - name: kube-openmpi-driver
        configMap:
          name: {{ .Release.Name }}-driver
      containers:
      - name: bootstrap
        image: {{ .Values.kubectlImage.repository }}:{{ .Values.kubectlImage.tag }}
        imagePullPolicy: {{ .Values.kubectlImage.pullPolicy }}
        resources:
{{ toYaml .Values.bootStrap.resources | indent 10 }}
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - |
                echo "preStop hook invoked."
                source /kube-openmpi-driver/util.sh
                stop_cluster
        volumeMounts:
        - name: manifests
          mountPath: /manifests
        - name: ssh-key
          mountPath: /ssh-key
        - name: kube-openmpi-driver
          mountPath: /kube-openmpi-driver
        env:
        - name: RENDERED_MANIFEST_DIR
          value: "/tmp/rendered-manifests"
        command:
        - sh
        - /kube-openmpi-driver/run.sh
